travis:
  secure:
    BINSTAR_TOKEN: grMYKgbRKdYZviLd5a+wYC5KKmmNqVxPaXGDSqugjDjVY8Cy6uWcPnQ4rAiKg3Ji/+KfpZpEBN9K+ZEe3gvgDe1wL8LgRAceCRVkoic0DqgPddfxxmjdycWVtmFOrrzLxh4Ag1GqUOCDWkJSex7FJDNyLVLl/p1FlT/d/dcIVy3HUsMcoW/oRgxr/EdNd4AWKUeg80Zjsp2+AGrqHPzPiE11jKqVCpuCkOitwCst1DEIw+hYlkg0egbcvjxZe0hsZBmdrj1jO23PzIWn+bEcl4x2QuK3Toy6YAvesZWxsVRveiFwKU0ckYcE9LtcW0A0WAidFA7uOXngKLl7xGZNGRWTxpeDUfH0LJbgl1xC4cOgFH7qx5aU834WhoREN2L/vVppUUdm3wj7IjT6Oa6z+RlRyyQ7OocMR5Ioz25mpmCoQvPgtXMLXy9aOPqFvsTpKl9D286tR+41wZM3MkL9LS3wneu+J1qNtgprT+q71gP3ng6ELgtxEV+dL1LU4pbmniL+a5i4Y51l1sz595Tdg2Gq/tbJByuk6SW+BMRNxTIck9hnlFXQaGUOL8pzfneGNpAN4J/9jT9iEEwwTgWAN9v0JQRZA2oAdQB/it/89DHWj+WX9+oMD5gnUQgI+cx2LErVbmRipPS/nSFLoiRn0GV4MB5/9YcDbBdhjhzy+5c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
